apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "filebrowser.name" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "filebrowser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filebrowser.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "filebrowser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: create-folders-tree
        image: "{{ .Values.global.imageRegistry }}/utilsbox:stable"
        env:
    {{- if .Values.global.securityContext }}
        - name: UID
          value: {{ .Values.global.securityContext.runAsUser | quote }}
        - name: GID
          value: {{ .Values.global.securityContext.runAsGroup  | quote }}
    {{- else }}
        - name: UID
          value: {{ .Values.securityContext.runAsUser | quote }}
        - name: GID
          value: {{ .Values.securityContext.runAsGroup  | quote }}
    {{- end }}
        {{- if not ( (.Values.global.onyx).enabled | default false ) }}
        command:
          - "/bin/sh"
          - "-ecx"
          - |
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/sdk;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/audit;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/usage;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/resources;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/datasets;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/nlq;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/external-plugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/branding;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/styles;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/emails;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/exports;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/reports;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/notebooks;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/backups;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/samples;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/plugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/build-plugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/system_backups;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/translations;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/licensing;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/connectors;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/data;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/serverSidePlugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/custom-certificates;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/monitoring-custom-tests;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/farms;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/tenants;
            find /opt/sisense/storage -maxdepth 1 -type f -name "*report*.png" -print0 | xargs -0 rm -f;
            find /opt/sisense/storage/reports -type f -mtime +7 -name "*.png" -print0 | xargs -0 rm -f;
            chown -R $UID:$GID /opt/sisense/storage/plugins/ 2>/dev/null;
            touch /opt/sisense/storage/custom-certificates/ca-certificates.crt;
            chown -R $UID:$GID /opt/sisense/storage/custom-certificates/ 2>/dev/null;
        {{- else }}
        command:
          - "/bin/sh"
          - "-ecx"
          - |
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/sdk;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/audit;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/usage;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/resources;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/datasets;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/external-plugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/branding;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/styles;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/emails;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/exports;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/reports;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/notebooks;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/backups;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/samples;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/plugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/build-plugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/system_backups;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/translations;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/licensing;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/connectors;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/data;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/serverSidePlugins;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/custom-certificates;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/monitoring-custom-tests;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/farms;
            install -d -m 0755 -o $UID -g $GID /opt/sisense/storage/tenants;
            find /opt/sisense/storage -maxdepth 1 -type f -name "*report*.png" -print0 | xargs -0 rm -f;
            find /opt/sisense/storage/reports -type f -mtime +7 -name "*.png" -print0 | xargs -0 rm -f;
            chown -R $UID:$GID /opt/sisense/storage/plugins/ 2>/dev/null;
            touch /opt/sisense/storage/custom-certificates/ca-certificates.crt;
            chown -R $UID:$GID /opt/sisense/storage/custom-certificates/ 2>/dev/null;
        {{- end }}
        volumeMounts:
        - mountPath: /opt/sisense/storage
          name: storage
      containers:
        - name: {{ template "filebrowser.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /.filebrowser.json
              name: config
              subPath: .filebrowser.json
            - mountPath: /db
              name: db
            - mountPath: /rootdir
              name: rootdir
              readOnly: {{ .Values.rootDir.readOnly }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "filebrowser.fullname" . }}
        - name: db
          {{- if .Values.db.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvc.existingClaim | default (printf "%s-%s" (include "filebrowser.fullname" .) "db" ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: rootdir
          {{- if eq .Values.rootDir.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Values.rootDir.pvc.existingClaim | default (printf "%s-%s" (include "filebrowser.fullname" .) "rootdir" ) }}
            readOnly: {{ .Values.rootDir.readOnly }}
          {{- else if eq .Values.rootDir.type "hostPath" }}
          hostPath:
            path: {{ .Values.rootDir.hostPath.path }}
          {{- else }}
          emptyDir: {}
          {{- end }}